service: api-lambda
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-plugin-typescript
  - serverless-offline
functions:
  graphql:
    handler: graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
