previewsEnabled: true
services:
  - type: web
    name: api
    env: node
    region: frankfurt
    plan: starter
    healthCheckPath: /graphql/.well-known/apollo/server-health
    envVars:
      - fromGroup: trad-archive-preview
