service: api

useDotenv: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  # Settings to get ahead of deprecation warnings
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: "20201221"

functions:
  graphql:
    handler: src/serverless-handlers/graphql.handler
    environment:
      SERVERLESS_STAGE: ${opt:stage}
      WEB_ORIGIN: ${self:custom.webOrigin.${opt:stage}, self:custom.webOrigin.preview}
    memorySize: 2048
    timeout: 15
    events:
      - http:
          path: graphql
          method: post
          cors:
            origin: ${self:custom.webOrigin.${opt:stage}, self:custom.webOrigin.preview}
            allowCredentials: true
      - http:
          path: graphql
          method: get
          cors:
            origin: ${self:custom.webOrigin.${opt:stage}, self:custom.webOrigin.preview}
            allowCredentials: true
  importItmaAtomCollections:
    handler: src/serverless-handlers/importItmaAtomCollections.handler
    environment:
      SERVERLESS_STAGE: ${opt:stage}
    memorySize: 1024
    timeout: 600
    events:
      - schedule:
          rate: rate(24 hours)
          enabled: ${self:custom.shouldRunImportItmaAtomCollections.${opt:stage}, self:custom.shouldRunImportItmaAtomCollections.preview}
  importTunes:
    handler: src/serverless-handlers/importTunes.handler
    environment:
      SERVERLESS_STAGE: ${opt:stage}
    memorySize: 1024
    timeout: 240
    events:
      - schedule:
          rate: rate(24 hours)
          enabled: ${self:custom.shouldRunImportTunes.${opt:stage}, self:custom.shouldRunImportTunes.preview}
  keepWarm:
    handler: src/serverless-handlers/keepWarm.handler
    environment:
      SERVERLESS_STAGE: ${opt:stage}
    memorySize: 512
    timeout: 15
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: ${self:custom.shouldRunKeepWarm.${opt:stage}, self:custom.shouldRunKeepWarm.preview}

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

custom:
  webOrigin:
    dev: http://localhost:3000
    preview: https://trad-archive-git-${opt:stage}-dangurney.vercel.app
    prod: https://www.tradarchive.com
  shouldRunImportItmaAtomCollections:
    dev: false
    preview: true
    # TODO: Run on prod when environment is deployed
    prod: false
  shouldRunImportTunes:
    dev: false
    preview: true
    # TODO: Run on prod when environment is deployed
    prod: false
  shouldRunKeepWarm:
    dev: false
    preview: true
    # TODO: Run on prod when environment is deployed
    prod: false
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules:
      forceInclude:
        - pg
    packager: yarn
  customDomain:
    domainName: api-${opt:stage}.tradarchive.com
    certificateArn: arn:aws:acm:us-east-1:727441280422:certificate/2e5a0bc4-0c2b-43d4-a7a6-58eab5e3ea2b
    createRoute53Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    autoDomain: true
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    allowCache: true
    useChildProcesses: true
