service: trad-archive-api
provider:
  name: aws
  runtime: nodejs12.x
  # Settings to get ahead of deprecation warnings
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: '20201221'
functions:
  graphql:
    handler: src/apolloServer.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    useChildProcesses: true
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
