service: trad-archive-api

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  # Settings to get ahead of deprecation warnings
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: '20201221'

functions:
  graphql:
    handler: src/apolloServer.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors:
            origin: 'http://localhost:3000'
            allowCredentials: true

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceInclude:
        - pg
    packager: yarn
  customDomain:
    domainName: api.tradarchive.com
    basePath: ${opt.stage}
    certificateArn: arn:aws:acm:us-east-1:727441280422:certificate/2e5a0bc4-0c2b-43d4-a7a6-58eab5e3ea2b
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: http
    autoDomain: true
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
