service: trad-archive-api
provider:
  name: aws
  runtime: nodejs12.x
functions:
  graphql:
    handler: src/apolloServer.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          # TODO: Set allowed origins
          cors: true
      - http:
          path: graphql
          method: get
          # TODO: Set allowed origins
          cors: true
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 4000
  webpack:
    includeModules: true
