name: Branch - Deleted

on: delete

jobs:
  clean-up-planetscale-branch-and-ssm-envs:
    name: Delete PlanetScale DB branch and connection variables in AWS SSM
    runs-on: ubuntu-latest
    env:
      PLANETSCALE_SERVICE_TOKEN_NAME: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_NAME }}
      PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
    defaults:
      run:
        working-directory: api
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set branch name as env variable
        uses: nelonoel/branch-name@v1.0.1

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up pscale CLI
        run: |
          wget https://github.com/planetscale/cli/releases/download/v0.88.0/pscale_0.88.0_linux_amd64.deb
          sudo dpkg -i pscale_0.88.0_linux_amd64.deb

      - name: Delete pscale DB branch
        run: |
          pscale branch delete trad_archive ${BRANCH_NAME} --org tradarchive --force

      - name: Delete AWS SSM params for this branch
        run: |
          aws ssm delete-parameter --name /${BRANCH_NAME}/DATABASE_HOST
          aws ssm delete-parameter --name /${BRANCH_NAME}/DATABASE_USERNAME
          aws ssm delete-parameter --name /${BRANCH_NAME}/DATABASE_PASSWORD
          aws ssm delete-parameter --name /${BRANCH_NAME}/DATABASE_PORT
          aws ssm delete-parameter --name /${BRANCH_NAME}/DATABASE_NAME
