name: Branch - Deleted

on: delete

jobs:
  clean-up-planetscale-branch-and-ssm-envs:
    name: Delete PlanetScale DB branch
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    env:
      PLANETSCALE_SERVICE_TOKEN_NAME: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_NAME }}
      PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
    defaults:
      run:
        working-directory: remix
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set BRANCH_NAME as env variable
        run: |
          echo "BRANCH_NAME=$(echo ${{ github.event.ref }} | sed -e "s#refs/heads/##g")" >> $GITHUB_ENV

      - name: Set up pscale CLI
        run: |
          wget https://github.com/planetscale/cli/releases/download/v0.88.0/pscale_0.88.0_linux_amd64.deb
          sudo dpkg -i pscale_0.88.0_linux_amd64.deb

      - name: Delete pscale DB branch
        run: |
          echo "Deleting pscale DB branch ${{ env.BRANCH_NAME }}..."
          pscale branch delete trad_archive ${{ env.BRANCH_NAME }} --org tradarchive --force

      - name: Delete Vercel preview env variable
        run: |
          vercel link -p trad-archive --confirm --token ${{ secrets.VERCEL_SERVICE_TOKEN }}
          vercel env rm DATABASE_URL preview ${{ env.BRANCH_NAME }} --token ${{ secrets.VERCEL_SERVICE_TOKEN }} -y
