name: Branch - Created

on: create

jobs:
  create-planetscale-db-branch-and-set-ssm-envs:
    name: Create PlanetScale DB branch and set connection variables in AWS SSM
    runs-on: ubuntu-latest
    env:
      PLANETSCALE_SERVICE_TOKEN_NAME: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_NAME }}
      PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
    defaults:
      run:
        working-directory: api
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set branch name as env variable
        uses: nelonoel/branch-name@v1.0.1

      - name: Set up pscale CLI
        run: |
          wget https://github.com/planetscale/cli/releases/download/v0.91.0/pscale_0.91.0_linux_amd64.deb
          sudo dpkg -i pscale_0.91.0_linux_amd64.deb

      - name: Create pscale DB branch
        run: |
          pscale branch create trad_archive ${BRANCH_NAME} --org tradarchive --region us-east --from master

      - name: Create connection info for this DB branch
        id: create-password
        run: |
          JSON=$(pscale password create trad_archive ${BRANCH_NAME} ${{ github.sha }} --org tradarchive -f json)
          echo "::set-output name=dbHost::$(echo "${JSON}" | jq '.database_branch.access_host_url')"
          echo "::set-output name=dbUsername::$(echo "${JSON}" | jq '.id')"
          echo "::set-output name=dbPassword::$(echo "${JSON}" | jq '.plain_text')"

      - name: Save DB connection info as AWS SSM params
        run: |
          aws ssm put-parameter --name /${BRANCH_NAME}/DATABASE_HOST --value "${{ steps.create-password.outputs.dbHost }}" --type SecureString
          aws ssm put-parameter --name /${BRANCH_NAME}/DATABASE_USERNAME --value "${{ steps.create-password.outputs.dbUsername }}" --type SecureString
          aws ssm put-parameter --name /${BRANCH_NAME}/DATABASE_PASSWORD --value "${{ steps.create-password.outputs.dbPassword }}" --type SecureString
          aws ssm put-parameter --name /${BRANCH_NAME}/DATABASE_PORT --value "3306" --type SecureString
          aws ssm put-parameter --name /${BRANCH_NAME}/DATABASE_NAME --value "trad_archive" --type SecureString
