name: PR - Opened

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  create-planetscale-deploy-request:
    name: Create PlanetScale deploy request for this branch
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up pscale CLI
        run: |
          wget https://github.com/planetscale/cli/releases/download/v0.88.0/pscale_0.88.0_linux_amd64.deb
          sudo dpkg -i pscale_0.88.0_linux_amd64.deb

      - name: Open pscale deploy request for this branch
        run: |
          pscale dr create trad_archive ${{ github.ref }} --deploy-to master --service-token-name ${{ secrets.PSCALE_SERVICE_TOKEN_NAME }} --service-token ${{ secrets.PSCALE_SERVICE_TOKEN }}
